ARG ROCM_IMAGE=devenamd/rocm:3.6.0-200804

FROM $ROCM_IMAGE
MAINTAINER Deven Desai <deven.desai.amd@gmail.com>

ARG USER=rocm-user

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /home/$USER

# clone the official eigen repo from gitlab
RUN cd $HOME && git clone https://gitlab.com/libeigen/eigen eigen-official
RUN cd $HOME && ln -s eigen-official eigen

# copy the scripts to run the tests
COPY eigen/run_tests_nightly.rocm.sh $HOME/
COPY eigen/run_tests_gpu.rocm.sh $HOME/
