export MIOPEN_CHECK_NUMERICS=1
export MIOPEN_ENABLE_LOGGING=1

echo "MIOPEN_CHECK_NUMERICS=$MIOPEN_CHECK_NUMERICS"

python -c 'import os; print ("MIOPEN_CHECK_NUMERICS = ", os.environ["MIOPEN_CHECK_NUMERICS"])';
