
export TF_CPP_MIN_VLOG_LEVEL=2
# export TF_CPP_MIN_LOG_LEVEL=1
# export HCC_DB=0x48a
# export HIP_TRACE_API=2
# export MIOPEN_ENABLE_LOGGING=1
# export MIOPEN_ENABLE_LOGGING_CMD=1
# export TF_ROCM_ENABLE_FUSION=1

python3 $1

